# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'create_bag_0.ui'
#
# Created: Wed Sep 10 09:36:33 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_create_bag_0(object):
    def setupUi(self, create_bag_0):
        create_bag_0.setObjectName(_fromUtf8("create_bag_0"))
        create_bag_0.resize(596, 580)
        self.verticalLayoutWidget_2 = QtGui.QWidget(create_bag_0)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(420, 420, 160, 80))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.b_continue = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.b_continue.setObjectName(_fromUtf8("b_continue"))
        self.verticalLayout_2.addWidget(self.b_continue)
        self.b_cancel = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.b_cancel.setObjectName(_fromUtf8("b_cancel"))
        self.verticalLayout_2.addWidget(self.b_cancel)
        self.formLayoutWidget = QtGui.QWidget(create_bag_0)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 60, 381, 51))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.e_ppn = QtGui.QLineEdit(self.formLayoutWidget)
        self.e_ppn.setObjectName(_fromUtf8("e_ppn"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.e_ppn)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.e_source = QtGui.QLineEdit(self.formLayoutWidget)
        self.e_source.setObjectName(_fromUtf8("e_source"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.e_source)
        self.formLayoutWidget_2 = QtGui.QWidget(create_bag_0)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(30, 140, 381, 68))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.e_lang_title = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.e_lang_title.setObjectName(_fromUtf8("e_lang_title"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.e_lang_title)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.e_lang_subtitle = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.e_lang_subtitle.setObjectName(_fromUtf8("e_lang_subtitle"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.e_lang_subtitle)
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.formLayoutWidget_3 = QtGui.QWidget(create_bag_0)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(30, 230, 381, 86))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_8 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_8)
        self.e_uri_liveweb = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.e_uri_liveweb.setObjectName(_fromUtf8("e_uri_liveweb"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.e_uri_liveweb)
        self.label_7 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_7)
        self.e_uri_archiv = QtGui.QLineEdit(self.formLayoutWidget_3)
        self.e_uri_archiv.setObjectName(_fromUtf8("e_uri_archiv"))
        self.formLayout_3.setWidget(2, QtGui.QFormLayout.FieldRole, self.e_uri_archiv)
        self.label_9 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_9)
        self.formLayoutWidget_4 = QtGui.QWidget(create_bag_0)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(30, 340, 381, 94))
        self.formLayoutWidget_4.setObjectName(_fromUtf8("formLayoutWidget_4"))
        self.formLayout_4 = QtGui.QFormLayout(self.formLayoutWidget_4)
        self.formLayout_4.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout_4.setMargin(0)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_10 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_10)
        self.e_rights = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.e_rights.setObjectName(_fromUtf8("e_rights"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.FieldRole, self.e_rights)
        self.label_11 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_11)
        self.e_rights_holder = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.e_rights_holder.setObjectName(_fromUtf8("e_rights_holder"))
        self.formLayout_4.setWidget(3, QtGui.QFormLayout.FieldRole, self.e_rights_holder)
        self.label_12 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_12)
        self.e_mw_date = QtGui.QLineEdit(self.formLayoutWidget_4)
        self.e_mw_date.setObjectName(_fromUtf8("e_mw_date"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.FieldRole, self.e_mw_date)
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_4.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_6)

        self.retranslateUi(create_bag_0)
        QtCore.QMetaObject.connectSlotsByName(create_bag_0)
        create_bag_0.setTabOrder(self.e_ppn, self.e_source)
        create_bag_0.setTabOrder(self.e_source, self.e_lang_title)
        create_bag_0.setTabOrder(self.e_lang_title, self.e_lang_subtitle)
        create_bag_0.setTabOrder(self.e_lang_subtitle, self.e_uri_liveweb)
        create_bag_0.setTabOrder(self.e_uri_liveweb, self.e_uri_archiv)
        create_bag_0.setTabOrder(self.e_uri_archiv, self.e_rights)
        create_bag_0.setTabOrder(self.e_rights, self.e_mw_date)
        create_bag_0.setTabOrder(self.e_mw_date, self.e_rights_holder)
        create_bag_0.setTabOrder(self.e_rights_holder, self.b_continue)
        create_bag_0.setTabOrder(self.b_continue, self.b_cancel)

    def retranslateUi(self, create_bag_0):
        create_bag_0.setWindowTitle(_translate("create_bag_0", "Dialog", None))
        self.b_continue.setText(_translate("create_bag_0", "Weiter", None))
        self.b_cancel.setText(_translate("create_bag_0", "Abbrechen", None))
        self.label.setText(_translate("create_bag_0", "PPN", None))
        self.label_2.setText(_translate("create_bag_0", "Quelle", None))
        self.label_3.setText(_translate("create_bag_0", "Titel", None))
        self.label_4.setText(_translate("create_bag_0", "Untertitel", None))
        self.label_5.setText(_translate("create_bag_0", "Sprache", None))
        self.label_8.setText(_translate("create_bag_0", "URI", None))
        self.label_7.setText(_translate("create_bag_0", "Archiv", None))
        self.label_9.setText(_translate("create_bag_0", "Liveweb", None))
        self.label_10.setText(_translate("create_bag_0", "Rechte", None))
        self.label_11.setText(_translate("create_bag_0", "Inhaber", None))
        self.label_12.setText(_translate("create_bag_0", "Benutzung", None))
        self.label_6.setText(_translate("create_bag_0", "Moving Wall", None))

